# Generated by Django 4.0.4 on 2022-05-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
